### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by josegonzalez** [gerrymcdonnell/cakephp-jokeplugin#1]
:P

**Comment by gerrymcdonnell** [comment]
lol 
Just my first Cakephp 3 plugin its not much but was learning how to make plugins and use github and composer at the same time.

**Comment by josegonzalez** [comment]
Heh I thought I'd comment because of the name, all good :P

**Comment by gerrymcdonnell** [comment]
can i ask you a question about cakephp3? I posted one on stackoverflow could you help me out?
http://stackoverflow.com/questions/37413421/cakephp3-layout-size-with-zurb-foundation
